### ISSUE TITLE
looks promising, just 2 things...

### ISSUE THREAD

**Issue by MercyfulKing** [Noxeramas/AiVtuberV2#1]
I cloned the repo, saw that webui.bat has the code for install which is fine, but got errors looking for "data folder" which had the "config"  file. I simply copied it the to the appropriate folder so now I have 2 data folders, lol. doesn't matter. It worked and installed.  While oobabooga was open in the background, I selected it as my model but it did not connect. Can you throw up some instructions on how to install as I'm not sure if I did it correctly. Much appreciated. I've been looking for one of these vtubers to connect to oobabooga that can read chat for a long time. Really don't want to pay for chatgpt when I have llms locally.

**Comment by Noxeramas** [comment]
Hey thanks for the message. the project is in a very early alpha right now its effectively non working right now. It would be private until its ready but that required github premium. 
Currently in the process of converting over to a javascript base, it provides more tools for me to make the UI prettier and more reactive without turning it into a tkinter desktop app.
also yes, once its complete it will have full step by step instructions on how to install properly and all the requirements you need.
current options i plan to implement to avoid the use of chat gpt are as follows
oobabooga, characterai, and LM studio so youll have plenty of options as a user and a lot of modularity.

add a start to keep an eye on development if youre interested thanks!
